### ISSUE TITLE
Get rid of spurious 0 point at right-hand edge of graph

### ISSUE THREAD

**Issue by weinerjm** [mgrau/coronavirus#2]
The fact that the most recent point is 0 on the graph makes it look strange. It's not a real point and shouldn't have a line drawn to it.

**Comment by weinerjm** [comment]
The 0 point was a data issue coming from the raw data

**Comment by mgrau** [comment]
as of 97d6d2a2885cbb953572c686c064a74f231c221c these are now parsed out automatically.
